package nouralab.pkg04gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Payroll extends javax.swing.JFrame {

    ArrayList<Worker> workerList = new ArrayList<>();

    public Payroll() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNameSE = new javax.swing.JTextField();
        dropOption = new javax.swing.JComboBox<>();
        txtHoursSE = new javax.swing.JTextField();
        cbxMedIns = new javax.swing.JCheckBox();
        cbxDentIns = new javax.swing.JCheckBox();
        cbxDisIns = new javax.swing.JCheckBox();
        cbxRetIns = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHoursCP = new javax.swing.JTextField();
        txtNameCP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPositionCP = new javax.swing.JTextField();
        txtRateCP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtOvertimeCP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRegWageCP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtOvertimeWageCP = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTotalWageCP = new javax.swing.JTextField();
        cbxDisInsCP = new javax.swing.JCheckBox();
        cbxDentInsCP = new javax.swing.JCheckBox();
        cbxMedInsCP = new javax.swing.JCheckBox();
        cbxRetInsCP = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        txtTotalDeductionCP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNetPayCP = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        btnDeleteRecord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 4));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Employee Payroll System");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nouralab/pkg04gui/Dollar-USD-icon.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nouralab/pkg04gui/Dollar-USD-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 3, true), "Search Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Name");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Position");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Hours/w");

        txtNameSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameSEActionPerformed(evt);
            }
        });

        dropOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin A1", "Worker P1", "Worker P2" }));
        dropOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropOptionActionPerformed(evt);
            }
        });

        txtHoursSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoursSEActionPerformed(evt);
            }
        });

        cbxMedIns.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cbxMedIns.setText("Medical Insurance");
        cbxMedIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMedInsActionPerformed(evt);
            }
        });

        cbxDentIns.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cbxDentIns.setText("Dental Insurance");
        cbxDentIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDentInsActionPerformed(evt);
            }
        });

        cbxDisIns.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cbxDisIns.setText("Disability Insurance");
        cbxDisIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDisInsActionPerformed(evt);
            }
        });

        cbxRetIns.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cbxRetIns.setText("Retirement Plan");
        cbxRetIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRetInsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameSE, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dropOption, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoursSE, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxDentIns)
                            .addComponent(cbxMedIns)
                            .addComponent(cbxDisIns)
                            .addComponent(cbxRetIns))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNameSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dropOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHoursSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(cbxMedIns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxDentIns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxDisIns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxRetIns)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 3, true), "Calculate Pay", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Hours/W");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Name");

        txtHoursCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoursCPActionPerformed(evt);
            }
        });

        txtNameCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameCPActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Position");

        txtPositionCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPositionCPActionPerformed(evt);
            }
        });

        txtRateCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRateCPActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Rate/h");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Overtime");

        txtOvertimeCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOvertimeCPActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Regular Wage");

        txtRegWageCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegWageCPActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("OverTime Wage");

        txtOvertimeWageCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOvertimeWageCPActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Total Wage");

        txtTotalWageCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalWageCPActionPerformed(evt);
            }
        });

        cbxDisInsCP.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cbxDisInsCP.setText("Disability Insurance");
        cbxDisInsCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDisInsCPActionPerformed(evt);
            }
        });

        cbxDentInsCP.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cbxDentInsCP.setText("Dental Insurance");
        cbxDentInsCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDentInsCPActionPerformed(evt);
            }
        });

        cbxMedInsCP.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cbxMedInsCP.setText("Medical Insurance");
        cbxMedInsCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMedInsCPActionPerformed(evt);
            }
        });

        cbxRetInsCP.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cbxRetInsCP.setText("Retirement Plan");
        cbxRetInsCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRetInsCPActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Total Deductions");

        txtTotalDeductionCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalDeductionCPActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Net Pay");

        txtNetPayCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetPayCPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalWageCP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOvertimeWageCP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegWageCP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNameCP, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(txtHoursCP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPositionCP))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txtRateCP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtOvertimeCP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxMedInsCP)
                                .addComponent(cbxDentInsCP))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxRetInsCP)
                                .addComponent(cbxDisInsCP))))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNetPayCP, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(18, 18, 18)
                            .addComponent(txtTotalDeductionCP, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNameCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPositionCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtHoursCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRateCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtOvertimeCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtRegWageCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtOvertimeWageCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTotalWageCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxMedInsCP)
                    .addComponent(cbxDisInsCP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDentInsCP)
                    .addComponent(cbxRetInsCP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTotalDeductionCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNetPayCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnCalculate.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Name", "Position", "Total Deductions", "Net Pay"
            }
        ));
        tblEmployees.setToolTipText("");
        jScrollPane1.setViewportView(tblEmployees);

        btnDeleteRecord.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnDeleteRecord.setText("Delete");
        btnDeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExit)
                            .addComponent(btnDeleteRecord))
                        .addGap(18, 18, 18)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalculate)
                            .addComponent(btnDeleteRecord))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReset)
                            .addComponent(btnExit)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameSEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameSEActionPerformed

    private void dropOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropOptionActionPerformed
        // TODO add your handling code here:
        String role = dropOption.getSelectedItem().toString().trim();
        if (role.equals("Admin A1")) {
            cbxMedIns.setEnabled(true);
            cbxDisIns.setEnabled(true);
            cbxDentIns.setEnabled(true);
            cbxRetIns.setEnabled(true);
        } else if (role.equals("Worker P1")) {
            cbxMedIns.setEnabled(true);
            cbxDisIns.setEnabled(true);
            cbxDentIns.setEnabled(true);
            cbxRetIns.setEnabled(false);
        } else if (role.equals("Worker P2")) {
            cbxMedIns.setEnabled(false);
            cbxDisIns.setEnabled(false);
            cbxDentIns.setEnabled(false);
            cbxRetIns.setEnabled(false);
        }

    }//GEN-LAST:event_dropOptionActionPerformed

    private void txtHoursSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoursSEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoursSEActionPerformed

    private void cbxMedInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMedInsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMedInsActionPerformed

    private void cbxDentInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDentInsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDentInsActionPerformed

    private void cbxDisInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDisInsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDisInsActionPerformed

    private void cbxRetInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRetInsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRetInsActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        String position = dropOption.getSelectedItem().toString().trim();
        if (!txtNameSE.getText().isEmpty()) {
            String name = txtNameSE.getText().toString().trim();
            int hours = 0;
            try {
                hours = Integer.parseInt(txtHoursSE.getText().toString().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Hours/W should be a number");
            }
            boolean dentInsurance = cbxDentIns.isSelected();
            boolean medINsurance = cbxMedIns.isSelected();
            boolean retirementPlan = cbxRetIns.isSelected();
            boolean disInsurance = cbxDisIns.isSelected();
            Worker w = new Worker(name, position, hours, medINsurance, dentInsurance, disInsurance, retirementPlan);

            txtNameCP.setText(w.getName());
            txtPositionCP.setText(w.getPosition());
            txtHoursCP.setText(w.getHours() + "");
            txtOvertimeCP.setText(w.getOverTime() + "");
            txtRateCP.setText(w.getHourRate() + "");
            txtRegWageCP.setText(w.getRegWage() + "");
            txtOvertimeWageCP.setText(w.getOvertimeWage() + "");
            txtTotalWageCP.setText(w.getTotalWage() + "");
            txtTotalDeductionCP.setText(w.getTotalDeductions() + "");
            txtNetPayCP.setText(w.getNetPay() + "");

            if (position.equals("Admin A1")) {
                cbxDentInsCP.setSelected(w.isDentalInsurance());
                cbxMedInsCP.setSelected(w.isMedicalInsurance());
                cbxRetInsCP.setSelected(w.isRetirementPlan());
                cbxDisInsCP.setSelected(w.isDisAbilityInsurance());
            } else if (position.equals("Worker P1")) {
                cbxDentInsCP.setSelected(w.isDentalInsurance());
                cbxMedInsCP.setSelected(w.isMedicalInsurance());
                cbxRetInsCP.setSelected(w.isRetirementPlan());
                cbxRetIns.setEnabled(false);
            } else if (position.equals("Worker P2")) {
                cbxMedIns.setEnabled(false);
                cbxDisIns.setEnabled(false);
                cbxDentIns.setEnabled(false);
                cbxRetIns.setEnabled(false);
            }
            workerList.add(w);
            resetFields();
            refreshTable();
        } else {
            JOptionPane.showMessageDialog(null, "Name shouldn't be empty");
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void txtNetPayCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetPayCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNetPayCPActionPerformed

    private void txtTotalDeductionCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalDeductionCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalDeductionCPActionPerformed

    private void cbxRetInsCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRetInsCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRetInsCPActionPerformed

    private void cbxMedInsCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMedInsCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMedInsCPActionPerformed

    private void cbxDentInsCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDentInsCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDentInsCPActionPerformed

    private void cbxDisInsCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDisInsCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDisInsCPActionPerformed

    private void txtTotalWageCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalWageCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalWageCPActionPerformed

    private void txtOvertimeWageCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOvertimeWageCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOvertimeWageCPActionPerformed

    private void txtRegWageCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegWageCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegWageCPActionPerformed

    private void txtOvertimeCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOvertimeCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOvertimeCPActionPerformed

    private void txtRateCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRateCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRateCPActionPerformed

    private void txtPositionCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPositionCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPositionCPActionPerformed

    private void txtNameCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameCPActionPerformed

    private void txtHoursCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoursCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoursCPActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetFields();

    }//GEN-LAST:event_btnResetActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRecordActionPerformed

        DefaultTableModel tableModel = (DefaultTableModel) tblEmployees.getModel();
        if (tblEmployees.getSelectedRowCount() == 1) {
            int rowIndex = tblEmployees.getSelectedRow();
            tableModel.removeRow(rowIndex);
            workerList.remove(rowIndex);
        }
    }//GEN-LAST:event_btnDeleteRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnDeleteRecord;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox cbxDentIns;
    private javax.swing.JCheckBox cbxDentInsCP;
    private javax.swing.JCheckBox cbxDisIns;
    private javax.swing.JCheckBox cbxDisInsCP;
    private javax.swing.JCheckBox cbxMedIns;
    private javax.swing.JCheckBox cbxMedInsCP;
    private javax.swing.JCheckBox cbxRetIns;
    private javax.swing.JCheckBox cbxRetInsCP;
    private javax.swing.JComboBox<String> dropOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JTextField txtHoursCP;
    private javax.swing.JTextField txtHoursSE;
    private javax.swing.JTextField txtNameCP;
    private javax.swing.JTextField txtNameSE;
    private javax.swing.JTextField txtNetPayCP;
    private javax.swing.JTextField txtOvertimeCP;
    private javax.swing.JTextField txtOvertimeWageCP;
    private javax.swing.JTextField txtPositionCP;
    private javax.swing.JTextField txtRateCP;
    private javax.swing.JTextField txtRegWageCP;
    private javax.swing.JTextField txtTotalDeductionCP;
    private javax.swing.JTextField txtTotalWageCP;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
        DefaultTableModel tableModel = (DefaultTableModel) tblEmployees.getModel();
        tableModel.getDataVector().removeAllElements();
        revalidate();
        for (Worker worker : workerList) {
            String rowData[] = {worker.getName().toString(), worker.getPosition().toString(), worker.getTotalDeductions() + "", worker.getNetPay() + ""};
            tableModel.addRow(rowData);
        }
    }

    private void resetFields() {
        txtNameSE.setText("");
        txtHoursSE.setText("");
        txtNameCP.setText("");
        txtPositionCP.setText("");
        txtHoursCP.setText("");
        txtOvertimeCP.setText("");
        txtRateCP.setText("");
        txtRegWageCP.setText("");
        txtOvertimeWageCP.setText("");
        txtTotalWageCP.setText("");
        txtTotalDeductionCP.setText("");
        txtNetPayCP.setText("");
        cbxMedIns.setSelected(false);
        cbxDisIns.setSelected(false);
        cbxDentIns.setSelected(false);
        cbxRetIns.setSelected(false);
    }
}
